/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printInput(Input p)
{
  _n_ = 0;
  bufReset();
  ppInput(p, 0);
  return buf_;
}
char *showInput(Input p)
{
  _n_ = 0;
  bufReset();
  shInput(p);
  return buf_;
}
void ppInput(Input p, int _i_)
{
  switch(p->kind)
  {
  case is_StartInput:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListCommand(p->u.startInput_.listcommand_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void ppCommand(Command p, int _i_)
{
  switch(p->kind)
  {
  case is_SimpleCmd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSimpleCommand(p->u.simpleCmd_.simplecommand_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PipeCmd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPipeline(p->u.pipeCmd_.pipeline_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_AICmd:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("AI");
    ppListWord(p->u.aICmd_.listword_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Command!\n");
    exit(1);
  }
}

void ppPipeline(Pipeline p, int _i_)
{
  switch(p->kind)
  {
  case is_PipeLine:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListSimpleCommand(p->u.pipeLine_.listsimplecommand_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void ppSimpleCommand(SimpleCommand p, int _i_)
{
  switch(p->kind)
  {
  case is_Cmd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.cmd_.word_, 0);
    ppListWord(p->u.cmd_.listword_, 0);
    ppListRedirection(p->u.cmd_.listredirection_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SimpleCommand!\n");
    exit(1);
  }
}

void ppRedirection(Redirection p, int _i_)
{
  switch(p->kind)
  {
  case is_RedirIn:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    ppIdent(p->u.redirIn_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RedirOut:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    ppIdent(p->u.redirOut_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_RedirAppend:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">>");
    ppIdent(p->u.redirAppend_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Redirection!\n");
    exit(1);
  }
}

void ppListCommand(ListCommand listcommand, int i)
{
  if (listcommand == 0)
  { /* nil */
  }
  else if (listcommand->listcommand_ == 0)
  { /* last */
    ppCommand(listcommand->command_, 0);
  }
  else
  { /* cons */
    ppCommand(listcommand->command_, 0);
    renderC(';');
    ppListCommand(listcommand->listcommand_, 0);
  }
}

void ppListSimpleCommand(ListSimpleCommand listsimplecommand, int i)
{
  if (listsimplecommand == 0)
  { /* nil */
  }
  else if (listsimplecommand->listsimplecommand_ == 0)
  { /* last */
    ppSimpleCommand(listsimplecommand->simplecommand_, 0);
  }
  else
  { /* cons */
    ppSimpleCommand(listsimplecommand->simplecommand_, 0);
    renderC('|');
    ppListSimpleCommand(listsimplecommand->listsimplecommand_, 0);
  }
}

void ppListWord(ListWord listword, int i)
{
  if (listword == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppIdent(listword->word_, 0); ppListWord(listword->listword_, 0);
  }
}

void ppListRedirection(ListRedirection listredirection, int i)
{
  if (listredirection == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppRedirection(listredirection->redirection_, 0);
    ppListRedirection(listredirection->listredirection_, 0);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppWord(String s, int i)
{
  renderS(s);
}


void shInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    bufAppendC('(');

    bufAppendS("StartInput");

    bufAppendC(' ');

    shListCommand(p->u.startInput_.listcommand_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Input!\n");
    exit(1);
  }
}

void shCommand(Command p)
{
  switch(p->kind)
  {
  case is_SimpleCmd:
    bufAppendC('(');

    bufAppendS("SimpleCmd");

    bufAppendC(' ');

    shSimpleCommand(p->u.simpleCmd_.simplecommand_);

    bufAppendC(')');

    break;
  case is_PipeCmd:
    bufAppendC('(');

    bufAppendS("PipeCmd");

    bufAppendC(' ');

    shPipeline(p->u.pipeCmd_.pipeline_);

    bufAppendC(')');

    break;
  case is_AICmd:
    bufAppendC('(');

    bufAppendS("AICmd");

    bufAppendC(' ');

    shListWord(p->u.aICmd_.listword_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Command!\n");
    exit(1);
  }
}

void shPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_PipeLine:
    bufAppendC('(');

    bufAppendS("PipeLine");

    bufAppendC(' ');

    shListSimpleCommand(p->u.pipeLine_.listsimplecommand_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Pipeline!\n");
    exit(1);
  }
}

void shSimpleCommand(SimpleCommand p)
{
  switch(p->kind)
  {
  case is_Cmd:
    bufAppendC('(');

    bufAppendS("Cmd");

    bufAppendC(' ');

    shIdent(p->u.cmd_.word_);
  bufAppendC(' ');
    shListWord(p->u.cmd_.listword_);
  bufAppendC(' ');
    shListRedirection(p->u.cmd_.listredirection_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SimpleCommand!\n");
    exit(1);
  }
}

void shRedirection(Redirection p)
{
  switch(p->kind)
  {
  case is_RedirIn:
    bufAppendC('(');

    bufAppendS("RedirIn");

    bufAppendC(' ');

    shIdent(p->u.redirIn_.word_);

    bufAppendC(')');

    break;
  case is_RedirOut:
    bufAppendC('(');

    bufAppendS("RedirOut");

    bufAppendC(' ');

    shIdent(p->u.redirOut_.word_);

    bufAppendC(')');

    break;
  case is_RedirAppend:
    bufAppendC('(');

    bufAppendS("RedirAppend");

    bufAppendC(' ');

    shIdent(p->u.redirAppend_.word_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Redirection!\n");
    exit(1);
  }
}

void shListCommand(ListCommand listcommand)
{
  bufAppendC('[');
  while(listcommand != 0)
  {
    if (listcommand->listcommand_)
    {
      shCommand(listcommand->command_);
      bufAppendS(", ");
      listcommand = listcommand->listcommand_;
    }
    else
    {
      shCommand(listcommand->command_);
      listcommand = 0;
    }
  }
  bufAppendC(']');
}

void shListSimpleCommand(ListSimpleCommand listsimplecommand)
{
  bufAppendC('[');
  while(listsimplecommand != 0)
  {
    if (listsimplecommand->listsimplecommand_)
    {
      shSimpleCommand(listsimplecommand->simplecommand_);
      bufAppendS(", ");
      listsimplecommand = listsimplecommand->listsimplecommand_;
    }
    else
    {
      shSimpleCommand(listsimplecommand->simplecommand_);
      listsimplecommand = 0;
    }
  }
  bufAppendC(']');
}

void shListWord(ListWord listword)
{
  bufAppendC('[');
  while(listword != 0)
  {
    if (listword->listword_)
    {
      shWord(listword->word_);
      bufAppendS(", ");
      listword = listword->listword_;
    }
    else
    {
      shWord(listword->word_);
      listword = 0;
    }
  }
  bufAppendC(']');
}

void shListRedirection(ListRedirection listredirection)
{
  bufAppendC('[');
  while(listredirection != 0)
  {
    if (listredirection->listredirection_)
    {
      shRedirection(listredirection->redirection_);
      bufAppendS(", ");
      listredirection = listredirection->listredirection_;
    }
    else
    {
      shRedirection(listredirection->redirection_);
      listredirection = 0;
    }
  }
  bufAppendC(']');
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shWord(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

