/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitInput(Input p);
void visitCommand(Command p);
void visitListCommand(ListCommand p);
void visitListWord(ListWord p);

void visitWord(Word p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

