/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    /* Code for StartInput Goes Here */
    visitListCommand(p->u.startInput_.listcommand_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitCommand(Command p)
{
  switch(p->kind)
  {
  case is_SimpleCmd:
    /* Code for SimpleCmd Goes Here */
    visitWord(p->u.simpleCmd_.word_);
    visitListWord(p->u.simpleCmd_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Command!\n");
    exit(1);
  }
}

void visitListCommand(ListCommand listcommand)
{
  while(listcommand  != 0)
  {
    /* Code For ListCommand Goes Here */
    visitCommand(listcommand->command_);
    listcommand = listcommand->listcommand_;
  }
}

void visitListWord(ListWord listword)
{
  while(listword  != 0)
  {
    /* Code For ListWord Goes Here */
    visitWord(listword->word_);
    listword = listword->listword_;
  }
}

void visitWord(Word p)
{
  /* Code for Word Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

